# Generated by Django 2.2.6 on 2019-12-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Strong Alcohol'), ('SW', 'midlle Alcohol'), ('OW', 'week')], max_length=2),
        ),
    ]
